project:
  type: website
  output-dir: docs
execute:
  freeze: auto
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
website:
  title: "David Munoz Tord"
  description: "David Munoz Tord's personal website"
  favicon: "images/me.png"
  google-analytics: "G-6KTW1Z7J25"
  twitter-card:
    creator: "@munoztd0"
  site-url: https://munoztd0.github.io/homepage/
  repo-url: https://github.com/munoztd0/homepage.github.io
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: "images/rbmv-secondary.png"
    background: primary
    search: true
    left:
      - text: "{{< fa house-user >}} Home"
        href: index.qmd
      - text: "{{< fa laptop-code >}} Blog"
        href: blog.qmd
      - text: "{{< fa chalkboard-user >}} Talks"
        href: talks.qmd
      - text: "{{< fa chart-line >}} Projects"
        href: projects.qmd
      - text: "{{< fa address-card >}} About"
        href: about.qmd
      - text: "{{< fa paperclip >}} Vitae"
        href: https://github.com/munoztd0/CV_DMT/raw/main/CV_DMT.pdf
      - text: "{{< fa paper-plane >}} Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/munoztd0
      - icon: youtube
        href: https://www.youtube.com/@wedata_unige
      - icon: twitter
        href: https://twitter.com/tord_munoz
      - icon: linkedin
        href: https://www.linkedin.com/in/david-munoz-tord-409639150/
  page-footer:
    background: primary
    left: "{{< fa copyright >}} 2024, David Munoz Tord"
    center:
      - text: "<img src='/images/rbmv-secondary.png' width='auto' height='30px'>"
    right:
      - icon: github
        href: https://github.com/munoztd0
      - icon: youtube
        href: https://www.youtube.com/@wedata_unige
      - icon: twitter
        href: https://twitter.com/tord_munoz
      - icon: linkedin
        href: https://www.linkedin.com/in/david-munoz-tord-409639150/




